image: docker:24.0

services:
  - docker:dind

stages:
  - build
  - deploy

variables:
  AWS_ACCOUNT_ID: "881490100310"
  AWS_DEFAULT_REGION: "us-east-1"
  APP_NAME: "app-eks-app"
  ECR_REPO: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
  IMAGE_TAG: "$CI_COMMIT_SHORT_SHA"  # ← hash do commit
  CLUSTER_NAME: "app-eks-cluster"
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  EFS_SERVER: fs-0fe05378af1ab65b8.efs.us-east-1.amazonaws.com
  SECRET_NAME: s3-credentials

before_script:
  - apk add --no-cache curl git unzip python3 py3-pip gettext
  - python3 -m venv /opt/venv
  - source /opt/venv/bin/activate
  - pip install --upgrade awscli
  - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
  - install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
  - aws configure set aws_access_key_id ${AWS_ACCESS_KEY_ID}
  - aws configure set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY}
  - aws configure set region ${AWS_DEFAULT_REGION}

build:
  stage: build
  script:
    - echo "Construindo a imagem Docker..."
    - docker build -t ${APP_NAME}:${IMAGE_TAG} .
    - echo "Autenticando no ECR..."
    - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${ECR_REPO}
    - echo "Taggeando a imagem..."
    - docker tag ${APP_NAME}:${IMAGE_TAG} ${ECR_REPO}/${APP_NAME}:${IMAGE_TAG}
    - echo "Enviando a imagem para o ECR..."
    - docker push ${ECR_REPO}/${APP_NAME}:${IMAGE_TAG}
  only:
    - main

deploy:
  stage: deploy
  script:
    - echo "Configurando o acesso ao cluster EKS..."
    - aws eks update-kubeconfig --name ${CLUSTER_NAME} --region ${AWS_DEFAULT_REGION}
    - export IMAGE="${ECR_REPO}/${APP_NAME}:${IMAGE_TAG}"  # ← substitui no YAML
    - echo "Implantando a aplicação no Kubernetes..."
    - envsubst < k8s/app/1-pv.yaml | kubectl apply -f -
    - envsubst < k8s/app/2-pvc.yaml | kubectl apply -f -
    - envsubst < k8s/app/3-deployment.yaml | kubectl apply -f -
  only:
    - main
