apiVersion: v1
kind: Namespace
metadata:
  name: app
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-storage-class
provisioner: efs.csi.aws.com
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv
  namespace: app
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /  # dir no EFS onde os logs serão armazenados
    server: fs-051f9372239145640.efs.us-east-1.amazonaws.com
  storageClassName: efs-storage-class
