apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: app
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: ${SECRET_NAME}
        objectType: secretsmanager
        objectAlias: ${SECRET_NAME}-secret
        jmesPath:
          - path: AWS_ACCESS_KEY_ID
            objectAlias: aws-access-key-id
          - path: AWS_SECRET_ACCESS_KEY
            objectAlias: aws-secret-access-key
          - path: AWS_DEFAULT_REGION
            objectAlias: aws-default-region
          - path: S3_BUCKET_NAME
            objectAlias: s3-bucket-name
  secretObjects:
    - secretName: api-token
      type: Opaque
      data:
        - objectName: aws-access-key-id
          key: aws-access-key-id
        - objectName: aws-secret-access-key
          key: aws-secret-access-key
        - objectName: aws-default-region
          key: aws-default-region
        - objectName: s3-bucket-name
          key: s3-bucket-name